### ISSUE TITLE
1.19.3 update?

### ISSUE THREAD

**Issue by Dreki1984** [FlynnLies/rechiseled_compat#1] opened 2023-04-17 17:25 UTC
Title, because there's so much unused mod wood in our storage on my server...

**Comment by FlynnLies** [comment] 2023-04-17 18:26
Sure, will take a few days though probably

**Comment by Dreki1984** [comment] 2023-04-17 19:39
Legend, thanks.

**Comment by FlynnLies** [comment] 2023-04-19 20:40
Didn't test this on a dedicated server yet, tags might break or something but should be fine otherwise. Will look over it on the weekend probably again and then close this if it works as intended.

For now have this pre-release [#v1.1.2-1.19.3](https://github.com/FlynnLies/rechiseled_compat/releases/tag/v1.1.2-1.19.3)

**Comment by Dreki1984** [comment] 2023-04-20 07:56
Cool, thanks! Legend.

**Comment by FlynnLies** [comment] 2023-04-21 18:36
Seems like everything is working fine, so [v1.1.2-1.19.3](https://github.com/FlynnLies/rechiseled_compat/releases/tag/v1.1.2-1.19.3) is now the actual release.

**Closed as completed by FlynnLies** 2023-04-21 18:36 UTC
Labels: enhancement
